### ISSUE TITLE
Windows lock

### ISSUE THREAD

**Issue by TiagoRocha1985** [Metallicow/Logitech-Gaming-Keyboard-Profiles#1]
Can you create a profile for when Windows is blocked?

I ask this because I wanted a profile with the lighting off when windows was locked, because after 5 minutes my windows lock, the monitors turn off but the keyboard does not = /

**Comment by Metallicow** [comment]
Most of what is here is based off the default software versions. I cannot help you with driver related issues or your own custom profiles. You can download the G software from logitech's website and install it, and if the profiles here do not work/import correctly you might be able to open them up in a text editor and update them manually. Most of the profiles here are just for basic commands which can then be combined into macros or on-the-fly scripted commands. Sorry I don't play around with lighting with these. You probably have a newer G-Keyboard than the G15 or G11.
